<?php

namespace AppBundle\Repository;

/**
 * UserOfferBookmarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOfferBookmarkerRepository extends \Doctrine\ORM\EntityRepository
{
}
